# Development 
version: '3.8'

services:
  app:
    # build the image from the dockerfile we created
    build: .
    environment:
      - NODE_ENV=dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  db:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    # stateful data even when the container is shutdown
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
